Added info about Timofei Rachkovsky
biodranik/landing-hugo pull request #23
Opened 2018-05-04 14:23 UTC by yaramk

There are three changes to the site:
1. Eng description of Timofei Rachkovsky 
2. Ru description of Timofei Rachkovsky  
3. Photo of Timofei Rachkovsky

2018-05-04 14:59 UTC, biodranik commented
Неплохо для начала, но есть нюансы в текстах. Подробнее отпишу позже.

2018-05-04 15:17 UTC, yaramk commented
Хорошо! Спасибо!

пт, 4 мая 2018, 5:59 PM Alexander Borsuk <notifications@github.com>:

> Неплохо для начала, но есть нюансы в текстах. Подробнее отпишу позже.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/biodranik/landing-hugo/pull/23#issuecomment-386628381>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AlJ5CF5NkpNar6wZOMO6KwrYhtzvvUXHks5tvGy4gaJpZM4TyvIx>
> .
>

2018-05-04 19:18 UTC, biodranik requested changes

2018-05-04 19:18 UTC, biodranik commented on content/team/Timofei Rachkovsky.ru.md
> +job_title: Design Engineer, магистрант
Инженер-проектировщик, магистрант

2018-05-04 19:18 UTC, biodranik commented on content/team/Timofei Rachkovsky.md
> +description: In VibroBox team Timofei is Design Engineer. He develops and tests hardware and firmware, as well as responsible for the developing signal processing modules in the spectral domain and d
As a Design Engineer, Timofei develops and tests our hardware and firmware. He is also responsible for the development of signal processing algorithms in the spectral domain and data acquisition subsystems.

2018-05-04 19:18 UTC, biodranik commented on content/team/Timofei Rachkovsky.md
> +keywords: Timofei Rachkovsky, design engineer, Master's Degree student, VibroBox, Digital Signal Processing, software testing, hardware testing
, firmware, spectral domain, data acquisition

2018-05-04 19:18 UTC, biodranik commented on content/team/Timofei Rachkovsky.md
> +In VibroBox team Timofei is Design Engineer. He develops and tests hardware and firmware, as well as responsible for the developing signal processing modules in the spectral domain and data acquisiti
```
As a Design Engineer, Timofei develops and tests our hardware and firmware. He is also responsible for:

* development of signal processing algorithms in the spectral domain;
* data acquisition subsystems;
* data processing framework/UI interaction API;
* user manuals for VibroBox products.

Timofei works in a close contact with other developers to maximize the effectiveness of the final product.
```

2018-05-04 19:18 UTC, biodranik commented on content/team/Timofei Rachkovsky.md
> +Timofei graduated from Belarusian State University of Informatics and Radioelectronics with a bachelor’s degree in Radioinformatics engineering. Timofei’s thesis theme is “Data gathering and transmis
... graduated in 20xx from ...

... theme was "Data collection and transmission unit for condition monitoring systems."

2018-05-04 19:18 UTC, biodranik commented on content/team/Timofei Rachkovsky.md
> +Now Timofei is a Master’s Degree student at BSUIR in the speciality of Radioengineering, including systems and devices for radionavigation, radar, and television. His thesis theme: “The condition mon
thesis theme is "Condition monitoring of machinery based on a packet wavelet transform."

2018-05-04 19:18 UTC, biodranik commented on content/team/Timofei Rachkovsky.ru.md
> +description: В проекте VibroBox Тимофей работает инженером-проектировщиком. Он разрабатывает и тестирует аппаратное и программное обеспечение, а также ответственен за разработку модулей цифровой обра
....а так же отвечает за разработку....

2018-05-04 19:18 UTC, biodranik commented on content/team/Timofei Rachkovsky.ru.md
> +keywords: Тимофей Рачковский, инженер-проектировщик, магистрант, VibroBox, цифровая обработка сигналов, тестирование программного обеспечения, тестирование аппаратного обеспечения.
лучше инженер и проектировщик разбить на два слова и через запятую, это кейворды для поисковиков.

2018-05-04 19:18 UTC, biodranik commented on content/team/Timofei Rachkovsky.ru.md
> +В проекте VibroBox Тимофей работает инженером-проектировщиком. Он разрабатывает и тестирует аппаратное и программное обеспечение, а также ответственен за разработку модулей цифровой обработки сигнало
... а так же отвечает за разработку...

2018-05-04 19:18 UTC, biodranik commented on content/team/Timofei Rachkovsky.ru.md
> +Тимофей получил степень бакалавра по специализации "Радиоинформатика" в Белорусском государственном университете информатики и радиоэлектроники. Защитил диплом по теме "Блок накопления и передачи дан
после названия универа можно написать в скобках (БГУИР) и в абзаце ниже использовать сокращение.

2018-05-06 16:14 UTC, yaramk commented on content/team/Timofei Rachkovsky.md
> +description: In VibroBox team Timofei is Design Engineer. He develops and tests hardware and firmware, as well as responsible for the developing signal processing modules in the spectral domain and d
Нужно уточнить про замену модулей алгоритмами.

2018-05-06 16:16 UTC, yaramk commented on content/team/Timofei Rachkovsky.md
> +In VibroBox team Timofei is Design Engineer. He develops and tests hardware and firmware, as well as responsible for the developing signal processing modules in the spectral domain and data acquisiti
Круто! Только опять про алгоритмы и модели нужно уточнить

2018-05-06 16:56 UTC, yaramk commented on content/team/Timofei Rachkovsky.md
> +In VibroBox team Timofei is Design Engineer. He develops and tests hardware and firmware, as well as responsible for the developing signal processing modules in the spectral domain and data acquisiti
а что такое "UI interaction API"?
Если это про пользовательский интерфейс, то Тимофей таким не занимается

2018-05-06 17:03 UTC, yaramk commented on content/team/Timofei Rachkovsky.ru.md
> +keywords: Тимофей Рачковский, инженер-проектировщик, магистрант, VibroBox, цифровая обработка сигналов, тестирование программного обеспечения, тестирование аппаратного обеспечения.
Мы с Тимофеем думаем, что это не совсем верно, т.к. получится две отдельные специальности.  Давай не будем менять. В русском яз это устоявшаяся специальность.

2018-05-06 21:34 UTC, biodranik commented on content/team/Timofei Rachkovsky.ru.md
> +keywords: Тимофей Рачковский, инженер-проектировщик, магистрант, VibroBox, цифровая обработка сигналов, тестирование программного обеспечения, тестирование аппаратного обеспечения.
Здесь кейворды, не имеющие никакого отношения к специальности. Это ключевые слова для поиска в некоторых поисковых системах. Разбивать имеет смысл, чтобы находило по отдельным словам инженер и проектировщик.

2018-05-06 21:34 UTC, biodranik approved these changes

2018-05-06 21:36 UTC, merged