Patch 1
biodranik/landing-hugo pull request #25
Opened 2018-05-10 16:58 UTC by yaramk

Here is A. Trus description to the site

2018-05-10 17:35 UTC, biodranik commented
Поревьюил. По ходу всплыла проблема, что нужно не забывать синхронизировать свою копию репозитория (форк) с основным репозиторием. Есть довольно мудрёная инструкция, как это делать здесь https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser

Более простой способ — дождаться, пока изменения БУДУТ ОДОБРЕНЫ и вмержены в основной репозиторий сайта (и появятся на нашем публичном сайте), и после этого УДАЛИТЬ свою копию репо (форк), и отфоркать его заново :)

2018-05-10 17:35 UTC, biodranik requested changes
Надо поправить мои комментарии.

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.md
> +description: In VibroBox team Aleksander is responsible for equipment design and unit manufacturing,  engineering, technology testing and certification.
Aleksandr

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.md
> +keywords: Aleksandr Trus, hardware, equipment, design, manufacturing, electronics, Chief Hardware Architect, Industry Expert, engineering, electronics, project management, industry, technology, certi
Aleksandr, Trus,
Chief, Hardware, Architect,
Industry, Expert,
project, management

Это кейворды для алгоритмов поиска, т.е. все "сложные" слова всегда лучше разбивать на составные.

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.md
> +Alexander is skilled Hardware Engineer and Architect with excellent knowledge of modern hardware, electronics, microelectronics and industrial automation. He has high-grade experience in designing, p
Aleksandr is a skilled hardware engineer and architect with an excellent knowledge of modern hardware, electronics, microelectronics and industrial automation. He has a vast experience in hardware design, production, testing and certification of multipurpose electrical and electronics devices intended for automation, telemetry data recording, collection, and transmitting. His area of expertise includes:

Нужно везде одинаково писать имя, это очень важно. Сбивает с толку читателя, если везде разный спеллинг.

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.md
> +
1. Не нужны пустые строки между элементами списка, только пустая строка перед началом списка и пустая строка после списка.
2. В Markdown для автоматической генерации непронумерованных списков надо вставлять либо дефисы -, либо звёздочки *

Подробнее про форматирование текста в Markdown можно прочитать здесь: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.md
> +• SCADA; PLC (Industrial Automation);
Это лучше на два элемента списка разбить.

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.md
> +• Digital and Analog Circuitry and Safety;
Не нужны точки с запятой в конце элементов списка, забивают восприятие. Возможно, будет так же лучше смотреться текст с маленьких букв, а то Не Очень Понятно, Почему Тут Тайтл Кейз.

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.md
> +• Digital and Analog Circuitry and Safety;
Кстати, по-русски тут что имелось ввиду? Перевод точно правильный?

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.md
> +• development and manufacturing sets of measurement equipment;
Пустую строку перед началом списка.

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.md
> +Education:
Можно подзаголовки 2-го или 3-го уровня выделять по правилам Markdown, см. по ссылке выше

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.md
> +From 1996 to 2001, Aleksandr studied at Belarusian State University of Informatics and Radioelectronics (BSUIR) at Faculty of Radioengineering and Electronics. In 2001 he graduated BSUIR in the speci
Aleksandr has studied at the faculty of Radioengineering and Electronics in Belarusian State University of Informatics and Radioelectronics (BSUIR) from 1996 to 2001. He got his Bachelor/Specialist degree in
Microelectronics as an Electronics Engineer.

Инженер-электрон[щ]ик же специальность?

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.ru.md
> +description: В команде VibroBox Александр отвечает за разработка и изготовление комплектов измерительного оборудования, техническую поддержку, разработку испытательного оборудования и аксессуаров, ра
за разработку

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.ru.md
> +keywords: Александр Трусь, аппаратное обеспечение, оборудование, проектирование оборудования, разработка, производство оборудования, электроника, главный конструктор, эксперт в отрасли, инженерия, эл
Точки в конце keywords не нужны.

Все слова без пробелов и разделителей, склоняемые одинаковые слова убираем, поисковики их сами умеют склонять.

Александр, Трусь, аппаратное, обеспечение, оборудование, проектирование, разработка, производство, электроника, главный, конструктор, эксперт, отрасли, инженерия, электроника, управление, проектами, промышленность, технология, сертификация, тестирование.

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.ru.md
> +* Цифровые и аналоговые схемы и безопасность;
Здесь правильно - со звёздочками. Точки с запятыми лучше убрать в конце, не нужны они для читателя. Возможно с маленьких букв начинать фразы, чтобы лучше читалось.

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.ru.md
> +* SCADA; PLC (промышленная автоматизация);
Разбить на две

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.ru.md
> +* Производство электроники, микроэлектроники Производство, тестирование и сертификация;
производство, тестирование и сертификация электроники и микроэлектроники

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.ru.md
> +* разработка и изготовление комплектов измерительного оборудования;
разработку

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.ru.md
> +* техническую документацию;
не нужны тут нигде точки с запятой, только мешают

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.ru.md
> +Образование:
Заголовок второго или третьего уровня будет так:
```
## Образование
или
### Образование
```

2018-05-10 17:35 UTC, biodranik commented on content/team/Aleksandr Trus.ru.md
> +С 1996 по 2001 Александр обучался в Белорусском университете информатики и радиоэлектронике (БГУИР) на факультете радиотехники и электроники. В 2001 он закончил БГУИР и и получил специализацию Микроэ
В 2001 он закончил БГУИР по специализации "микроэлектроника" и получил специальность "инженер электронной техники".

Только кавычки нужны русские.

2018-05-14 12:34 UTC, yaramk commented on content/team/Aleksandr Trus.md
> +• Digital and Analog Circuitry and Safety;
Что было по русски - не известно :) Я брала все это из CV и переводила на русский. Потом дала посмотреть Александру. Про англ он ничего не написал, а русскую почекал немного.

2018-05-14 12:34 UTC, yaramk commented on content/team/Aleksandr Trus.md
> +Alexander is skilled Hardware Engineer and Architect with excellent knowledge of modern hardware, electronics, microelectronics and industrial automation. He has high-grade experience in designing, p
Нужно все это и в CV перепроверить

2018-05-14 12:40 UTC, yaramk commented on content/team/Aleksandr Trus.md
> +Education:
Думаю, тут не нужно. Заменила на As to education ...

2018-05-14 12:40 UTC, yaramk commented on content/team/Aleksandr Trus.md
> +From 1996 to 2001, Aleksandr studied at Belarusian State University of Informatics and Radioelectronics (BSUIR) at Faculty of Radioengineering and Electronics. In 2001 he graduated BSUIR in the speci
специальность - инженер электронной техники

2018-05-14 12:51 UTC, yaramk commented on content/team/Aleksandr Trus.ru.md
> +keywords: Александр Трусь, аппаратное обеспечение, оборудование, проектирование оборудования, разработка, производство оборудования, электроника, главный конструктор, эксперт в отрасли, инженерия, эл
Тогда keywords нужно поменять у половины команды

2018-05-14 12:54 UTC, yaramk commented on content/team/Aleksandr Trus.ru.md
> +Образование:
Предлагаю образование всторить в предложение, как и в англ

2018-05-14 15:16 UTC, yaramk commented
Добавила Ивана Труса и обновила Александра Труся

2018-05-15 05:37 UTC, biodranik reviewed
Мне кажется, или два комментария остались не исправленными?

2018-05-17 16:33 UTC, yaramk commented on content/team/Aleksandr Trus.ru.md
> +С 1996 по 2001 Александр обучался в Белорусском университете информатики и радиоэлектронике (БГУИР) на факультете радиотехники и электроники. В 2001 он закончил БГУИР и и получил специализацию Микроэ
Тут все ок

2018-05-17 16:34 UTC, yaramk commented on content/team/Aleksandr Trus.md
> +description: In VibroBox team Aleksander is responsible for equipment design and unit manufacturing,  engineering, technology testing and certification.
тут тоже все ок

2018-05-17 18:15 UTC, biodranik requested changes
Два момента до сих пор не исправлены.

2018-05-17 18:15 UTC, biodranik commented on content/team/Aleksandr Trus.md
> +description: In VibroBox team Aleksander is responsible for equipment design and unit manufacturing,  engineering, technology testing and certification.
Aleksander же вместо Aleksandr, нужно исправить.

2018-05-17 18:15 UTC, biodranik commented on content/team/Aleksandr Trus.ru.md
> +description: В команде VibroBox Александр отвечает за разработка и изготовление комплектов измерительного оборудования, техническую поддержку, разработку испытательного оборудования и аксессуаров, ра
"вместо за разработка" надо "за разработку"

2018-05-17 23:33 UTC, aliakseimaniuk commented
@yaramk @biodranik можно без форка делать. Когда ты создвешь файл в репозитории, есть опция создать ветку. Возможно так будет удобнее.

2018-05-17 23:37 UTC, biodranik commented
@aliakseimaniuk только если есть доступ на модификацию репо (а его нет).

2018-05-24 15:43 UTC, biodranik commented on content/team/Aleksandr Trus.ru.md
> +description: В команде VibroBox Александр отвечает за разработка и изготовление комплектов измерительного оборудования, техническую поддержку, разработку испытательного оборудования и аксессуаров, ра
@yaramk исправишь здесь, пожалуйста?

2018-05-24 17:12 UTC, yaramk commented
Итак, у нас остался Игорь Лощинин, но его только на следующей или через неделю получится сделать, т.к. нет норм фото.
Остальное все ок?

2018-05-24 19:47 UTC, biodranik commented
Не нужно разные подзадачи скидывать в один пулл реквест. В данном случае надо было для разных людей делать разные, отдельные пулл реквесты, чтобы можно было дорабатывать тексты о каждом человеке отдельно и мержить их (публиковать на сайте) по мере готовности, а не накидывать всё в одну большую кучу, и долго-долго ждать, пока ВСЕ моменты для каждого человека будут исправлены.

2018-05-24 20:03 UTC, yaramk commented
Да, не права
Нужно что-то еще поправлять?

чт, 24 мая 2018, 10:47 PM Alexander Borsuk <notifications@github.com>:

> Не нужно разные подзадачи скидывать в один пулл реквест. В данном случае
> надо было для разных людей делать разные, отдельные пулл реквесты, чтобы
> можно было дорабатывать тексты о каждом человеке отдельно и мержить их
> (публиковать на сайте) по мере готовности, а не накидывать всё в одну
> большую кучу, и долго-долго ждать, пока ВСЕ моменты для каждого человека
> будут исправлены.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/biodranik/landing-hugo/pull/25#issuecomment-391836794>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AlJ5CGlnAandJFi7yA58caPDhUWFXnWaks5t1w4-gaJpZM4T6NiT>
> .
>

2018-05-29 05:06 UTC, biodranik commented
Изменения отсюда я вынес в отдельные реквесты по людям, это можно закрывать.

2018-05-29 05:06 UTC, closed without merging